\\Program to convert time into respective time formats i.e, 

(defn tim [a]\\for taking time as input
  (def b (quot a 60))
  (def c (quot b 60))
  (def d (quot c 24))
  (def e (quot d 7))
  (def g (rem a 60))
  (def h (rem b 60))
  (def i (rem c 24))
  (def j (rem d 7))
  (if (== b 0)
    (println g "sec")
    (if (== c 0)
      (println h "min"  g "sec")
      (if (== d 0)
        (println i "hr" h "min"  g "sec")
        (if (== e 0)
          (println j "day"  i "hr" h "min"  g "sec")
          (println e "wk" i "hr"  h "min"  g "sec")\\print time in wks,days,hrs resp
          )
        )
      )
    )
  )
